# Rename this to "movie-service.yml"!
# Fill your own data where you see "your...".

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/movie-app

  datasource:
    url: jdbc:postgresql://localhost:5432/yourdb
    username: yourusername
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: 8090