# Rename this to "payment-service.yml"!
# Fill your own data where you see "your...".

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yourdb
    username: yourusername
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    template:
      default-topic: payment-notification-topic

server:
  port: 8095

apiKey:
  stripeKey: yourStripeApiKey
  testSecret: yourStripeCliKey

payment:
  unit_amount: 1000
  default_currency: EUR
  success_url: http://localhost:8095/payments/success
  cancel_url: http://localhost:8095/payments/cancel